server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: cloud-notify
          uri: lb://cloud-notify/**
          predicates:
            - Path=/cloud-notify
          filters:
            - StripPrefix=1
        - id: cloud-auth
          uri: lb://cloud-auth/**
          predicates:
            - Path=/cloud-auth
          filters:
            - StripPrefix=1
        - id: cloud-admin
          uri: lb://cloud-admin
          predicates:
            - Path=/cloud-admin/**
          filters:
            - StripPrefix=1
        - id: cloud-svm
          uri: lb://cloud-svm
          predicates:
            - Path=/cloud-svm/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8080/cloud-auth/rsa/publicKey' #配置RSA的公钥访问地址
#  redis:
#    database: 0
#    port: 6379
#    host: localhost
#    password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/cloud-admin/admin/login"
      - "/cloud-auth/oauth/token"
      - "/cloud-auth/rsa/publicKey"
      - "/cloud-backend/admin/login"


management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
